# Part 2: Data Wrangling (Exploratory Data Analysis)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(5)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857

In [3]:
df.isnull().sum()/len(df)*100
# identify the percentage of null values in each attribute

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

In [4]:
df.dtypes

FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

## Task 1: Calculate the number of launches on each site

In [5]:
df['LaunchSite'].value_counts()
# CCAFS SLC 40 = CAPE CANAVERAL SPACE LAUNCH COMPLEX 40
# KSC LC 39A = KENNEDY SPACE CENTER LAUNCH COMPLEX 39A
# VAFB SLC 4E = VANDERBERG AIR FORCE BASE SPACE LAUNCH COMPLEX 4E

LaunchSite
CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

In [6]:
df['LaunchSite'].value_counts(normalize = True) * 100

LaunchSite
CCAFS SLC 40    61.111111
KSC LC 39A      24.444444
VAFB SLC 4E     14.444444
Name: proportion, dtype: float64

## Task 2: Calculate the number and ocurrence of mision outcome of the orbits

In [7]:
df[df['Orbit'] != 'GTO']['Orbit'].value_counts() 
## Not counting GTO, it is a transfer orbit and not Geostationary itself

Orbit
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
HEO       1
ES-L1     1
SO        1
GEO       1
Name: count, dtype: int64

In [8]:
df[df['Orbit'] != 'GTO']['Orbit'].value_counts(normalize = True) * 100

Orbit
ISS      33.333333
VLEO     22.222222
PO       14.285714
LEO      11.111111
SSO       7.936508
MEO       4.761905
HEO       1.587302
ES-L1     1.587302
SO        1.587302
GEO       1.587302
Name: proportion, dtype: float64

## Task 3: Calculate the number and occurence of mission outcome of the orbits

In [9]:
landing_outcomes = df['Outcome'].value_counts()

In [10]:
df['Outcome'].value_counts()

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

In [11]:
df['Outcome'].value_counts(normalize = True) * 100

Outcome
True ASDS      45.555556
None None      21.111111
True RTLS      15.555556
False ASDS      6.666667
True Ocean      5.555556
False Ocean     2.222222
None ASDS       2.222222
False RTLS      1.111111
Name: proportion, dtype: float64

In [12]:
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS

In [13]:
bad_outcomes = set(landing_outcomes.keys()[[1, 3, 5,6 ,7]])
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

## Task 4: Create a landing outcome label from Outcome column

In [14]:
landing_class = []

for outcome in df['Outcome']:
    if outcome in bad_outcomes:
        landing_class.append(0)
    else:
        landing_class.append(1)

df['Class'] = landing_class
df['Class'].head(5)

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [15]:
df.head(5)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857,0

In [16]:
df['Class'].mean()

np.float64(0.6666666666666666)

In [17]:
df['Class'].value_counts()

Class
1    60
0    30
Name: count, dtype: int64

Meaning that th succes rate is 67%

In [19]:
df.to_csv('dataset_part_2.csv', index = False)